# Numpy Exercices

- All the exercises in this section must be implemented using the `numpy` library.
- The vast majority of exercises can be solved **without** any `for` or `while` loop, just using Numpy's functions or vectorized operations.
- The vast majority of exercises can be solved with at most 1-6 lines of code.
- If you don't know how to solve something, feel free to search on the internet about your problem. For example, `"How to sort an array in numpy?"`.
- It is better if you don't use ChatGPT for finding the solution, so you get used to program with `numpy`.

In [51]:
import numpy as np

## Zeros

Initialize a null vector (with zeroes) of length 20.

In [52]:
vect = np.zeros(20)
print (vect)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Matrix Init

Initialize a null matrix (with zeros) with size 3x2.

In [53]:
mat = np.zeros((3,2))

print (mat)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Replace

Replace the minimum element of a random vector with a 0.

In [83]:
rng = np.random.default_rng()
a = rng.integers(0, 10, size=10)
print ("prima", a)
min_a = a.min()
print (min_a)

if min_a == 0:
    a[a==0] = 99
else:
    a[a==min_a]= 0

print ("dopo", a)

prima [4 0 1 8 6 4 2 0 3 4]
0
dopo [ 4 99  1  8  6  4  2 99  3  4]


## Consecutive

Create a vector with all consecutive values between 12 and 38.

In [88]:
b= np.arange(12,38)
print (b)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## Vector Init

Initialize a vector of length 10 with integer random numbers between 1 and 20.

In [90]:
rng = np.random.default_rng()
c = rng.integers(1, 20, size=10)
print ("prima", c)

prima [ 7 13  7 18 15 15 13 17 17 19]


a) Filter the elements that are greater than 3 and less than 12.

b) Filter the elemetns that are less than or equal to 5 or greater than 15.

## Random Matrix

Create a 4x4 matrix with integer random numbers between 0 and 5.

## Not Zero

Find the indices of the elements that are not 0 in the vector: [2, 1, 0, 0, 3, 1, 0].

In [55]:
v = np.array([2, 1, 0, 0, 3, 1, 0])

## Statistics

Create a random vector of length 10 and find the minimum, maximum, mean and standard deviation.

## Surround

Create a 10x10 matrix with zeroes inside and ones surrounding them, like the following:

```
[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]
```

## Zero Replace

Define a function that, given a vector, returns all the elements greater than 10 replaced by 0.

Example: [4, 7, 15, 21, 3, 34] → [4, 7, 0, 0, 3, 0]

## Negate

Define a function that negates (changes the sign) all the elements of a vector with values between 2 and 6.

Example: [4, 7, -6, 21, 3, 34] → [-4,  7, 6, 21, -3, 34]

## Matrix Negatives

Given a matrix containing both positive and negative numbers, modify it so:
- Each **positive number** remains unchanged.
- Each **negative number** is replaced by the sum of all positive numbers in the same column.

For example, this matrix:

```
np.array([
    [ 5, -2,  3],
    [-1,  4, -6],
    [ 2, -3,  1]
])
```

becomes:

```
np.array([
    [5, 4, 3],
    [7, 4, 4],
    [2, 4, 1]
])
```

Note: The `np.where()` function may be very useful.

In [56]:
m = np.array([
    [ 5, -2,  3],
    [-1,  4, -6],
    [ 2, -3,  1]
])

## Dates

Get the dates for today, yesterday and tomorrow. For today's date, you can use `np.datetime64('today')` then subtract or add 1 day to that.

## September

Get all dates in September 2023.

## Week

Create an array of dates starting from today and covering the next 7 days.

## Diff

Given an array of dates, find the differences (in days) between each date and the first date in days.

In [57]:
dates = np.array(['2023-08-14', '2023-08-17', '2023-08-20', '2025-10-10'], dtype='datetime64')

## Closest

Define a function `closest(v)` that, given a number $N$ and a vector, returns the element closest to $N$. In case of a tie return any element.

In [58]:
assert closest([1, 2, 3, 4], 2) == 2
assert closest([1, 2, 3, 4], 5) == 4
assert closest([1, 2, 3, 4], -3) == 1
assert closest([1, 2, 2, 3, 4], 2) == 2
assert closest([1, 2, 2, 3, 4], 2.4) == 2
assert closest([1, 2, 2, 3, 4], 2.6) == 3

NameError: name 'closest' is not defined

## N-Greater

Define a function that, given a positive number $N$ and a vector, returns the $N$ greater elements from the vector.

## Unique

Create a random vector of length 20 with values between 1 and 8. Which unique elements (without repetition) where created?

## NaN

What will be the result of the following statements?

First try to understand the concepts of `np.nan`, `np.inf` and `set`. Next, try to mentally solve the statements by using your logic. Finally, test if your expected results are correct. 

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
```

## Highest Mean

Given a 10x10 matrix of random values between 0 and 1, find and print the row with the highest mean value.

# Python vs Numpy

 For each one of the following exercises implement the functions using only Python, without any external libraries. Then compare the execution time with the `%%timeit` magic command (see the first example).

## Maximum

Write a function in Python that finds the maximum value of a list of numbers. Code it yourself, do not use the Python's `max()` function.

Create a list of random numbers with 10,000 elements or more.

Then test the average time it takes to run each of the `max` functions with the list (using the `%%timeit` magic command):
- Your custom `max` function.
- Python's built-in `max()` function.
- Numpy's `max()` function.

## Mean

Write a function in Python that finds the average value of a list of numbers. Code it yourself, do not use Numpy's `mean()` function.

Create a list of random numbers with 10,000 elements or more.

Then test the average time it takes to run each of the `mean` functions with the list (using the `%%timeit` magic command):
- Your custom `mean` function.
- Numpy's `mean()` function.

##  One-hot Encoding

Implement a function that returns a matrix with the one-hot encoding of a vector.

One-hot encoding: https://www.datacamp.com/tutorial/one-hot-encoding-python-tutorial

- Example: 
    - Input: [0, 2, 1, 2, 0, 1]
    - Output:
```
[[1., 0., 0.],
[0., 0., 1.],
[0., 1., 0.],
[0., 0., 1.],
[1., 0., 0.],
[0., 1., 0.]]
```

## Min-Max Scaling

Implement a function `minmax_scale(values)` that rescales a list (or NumPy array) of numeric values so that all values fall within the range **[0, 1]**. Specifically, the smallest number will have the value of $0$, while the largest one will have the value of $1$. The rest of the numbers will fall in between.

This kind of normalization is common in machine learning, ensuring that all features contribute equally to a model’s training process, regardless of their original scale.

Given an array of values $X$, the formula for Min-Max scaling for each one of its values $x_i$ is:

$x_i\_scaled = (x_i - min(X)) / (max(X) - min(X))$



## Fruit Ninja

You are a Fruit Ninja master, slicing fruits with precision. You have sliced 100 fruits, each giving you a random score between 1 and 100. However, due to a ninja technique, every third score is doubled. Calculate your total score.

## Time Traveler

A historian time traveler wants to study major events in the past century. Create an array of dates starting from 1923-08-14 to 2023-08-14 in 10-year increments, then randomly select 3 dates to travel to.

## Aliens

Aliens are transmitting binary messages — arrays of 100 elements containing only 0s and 1s.

However, their real message is hidden inside the signal: it always starts and ends with 1, and everything else before the first 1 and after the last 1 is just noise.

For example, given the message `[0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0]`, the real message you have to extract is the range from the first 1 until the last one, both included `[1, 0, 1, 1, 0, 0, 1]`.

In [ ]:
# Function that generates a random alien message

def get_aliens_message():
    # Creating a message where majority is zeros
    message = np.zeros(100, dtype=int)

    # Introducing the real message
    start_index = np.random.randint(10, 40)
    end_index = np.random.randint(60, 90)

    message[start_index:end_index] = np.random.randint(2, size=end_index-start_index)
    message[start_index] = 1
    message[end_index] = 1
    return message

In [ ]:
message = get_aliens_message()

## Temperature Log

Implement the function `detect_temperature_anomalies(values)`.

You have a 365-day temperature log for a city, represented as an array of floats. Identify the days where the temperature is at least 2 standard deviations away from the mean.

In [ ]:
# Simulated temperatures around 25°C with std deviation 5°C
temps = np.random.normal(25, 5, 365)
detect_temperature_anomalies(temps)

array([  6,  37,  81, 110, 146, 156, 161, 187, 192, 233, 263, 275, 318,
       336, 361])

## Max Pooling

In Convolutional Neural Networks (CNNs), used for image processing, there’s a step called max pooling. It helps reduce the size of a matrix (often an image) while keeping only the most important information — the maximum value within small regions.

Write a function `max_pooling(matrix)` that performs 2×2 max pooling on a given matrix. That is, for each 2×2 region, take the maximum value and add it to a new matrix. Finally, return the resulting smaller matrix.

If the input matrix has dimensions $m · n$, the resulting matrix will have dimensions $(m−1) · (n−1)$.

For example, for the input matrix

[

    [1, 3, 2, 4]

    [5, 6, 1, 0]

    [2, 8, 3, 1]

    [4, 7, 2, 5]
],

the resulting matrix from the max pooling operation is

[
   
    [6 6 4]

    [8 8 3]

    [8 8 5]
]

**Explanation**:
- The function slides a 2×2 window one step at a time.
- For the top-left region of 2×2 that contains the values 1, 3, 5 and 6, the maximum value is 6. This gives the first value in the top-left of the returned matrix.
- These repeats across the entire matrix for each 2×2 region.

In [ ]:
matrix = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 0],
    [2, 8, 3, 1],
    [4, 7, 2, 5],
])

## The Game of Life

Implement "The Game of Life" using Numpy.